package it.com.ibm.elux.spike;

import java.util.Random;

/**
 *
 */
public class Properties
{

    public static String getRandomName()
    {
        int propertyLen = Properties.getNames().length;
        int index = new Random().nextInt(propertyLen-1);
        return Properties.getNames()[index];
    }

    public static String getRandomUnit()
    {
        int propertyLen = Properties.getUnits().length;
        int index = new Random().nextInt(propertyLen-1);
        return Properties.getUnits()[index];
    }

    public static String getRandomString()
    {
        int propertyLen = Properties.getStrings().length;
        int index = new Random().nextInt(propertyLen-1);
        return Properties.getStrings()[index];
    }

    public static String[] getStrings()
    {
        return new String[]{
                "Running",
                "Paused",
                "Stand-By",
                "Temporary Locked",
                "Open",
                "Close",
                "Fix",
                "Stay",
                "Numbered",
                "Emerald",
                "Working"
        };
    }

    public static String[] getUnits()
    {
        return new String[]{
                "secs",
                "msecs",
                "min",
                "h",
                "days",
                "m",
                "km",
                "l",
                "ml"
        };
    }

    public static String[] getNames()
    {
        return new String[] {
                "Appliance Structure Type",
                "Appliance Serial Number",
                "Appliance Model Number",
                "Appliance Name",
                "Appliance NickName",
                "Appliance Brand Name",
                "Appliance PNC",
                "Configuration data size",
                "Configuration data values",
                "Appliance ELC",
                "Connectivity Node HW version",
                "Connectivity Node SW version",
                "Appliance UI HW version",
                "Appliance UI SW version",
                "Appliance UI Config. version",
                "Appliance MainBoard HW ver.",
                "Appliance MainBoard SW ver.",
                "Appliance MainBoard Cfg ver.",
                "Connectivity Node SW ANC",
                "Installation State",
                "Category Device Identifier",
                "Device Availability",
                "Device Link",
                "StartUp Command",
                "Device Uninstall",
                "Device Pres. And Searching",
                "Communication Link State",
                "Database Refresh",
                "Delete Device From Cloud",
                "NIU Reset",
                "Enable Appliance NIU Commun.",
                "NIU Leds Brightness",
                "Manufacturing Procedure State",
                "MAC Address",
                "RSSI Value",
                "Link Quality Indicator",
                "Network Interface Activation",
                "OTA Server Credential",
                "Cloud Agent Selection",
                "Local Agent Credentials",
                "Arrayent Agent Cloud Cred.",
                "IBM MQTT Agent Cloud Cred.",
                "Cloud Availability State",
                "OTA Server (cred. by) URL",
                "OTA Agent State",
                "NIU FW Update State",
                "NIU FW Update Command",
                "Network Name",
                "Own Network Name",
                "Service Discovery Information",
                "Service Discovery Introspect.",
                "Appliance Mode",
                "Appliance State",
                "Remote Control",
                "Execute Command",
                "End of Cycle Notification",
                "Appl/NIU Comm. Link State",
                "Network State Override",
                "Appliance Factory Reset",
                "User Acknowledge",
                "Running Time",
                "Time To End",
                "Start Time",
                "Stop Time",
                "Target Duration",
                "Reminder Time",
                "Selected Reminder Time",
                "Temperature Representation",
                "Time Format",
                "Language",
                "Sabbath Mode",
                "Vacation/Holiday Mode",
                "Silent Mode",
                "Energy Saving (ECO) Mode",
                "Hyper Mode",
                "Sleep Mode",
                "Display Light",
                "End Of Cycle Sound",
                "Ambient Temperature",
                "Display Temperature",
                "Target Temperature",
                "Actual Sensor Temperature",
                "Board Temperature",
                "Current Power",
                "Current Energy Use",
                "Current Energy Use (percent)",
                "Fan State",
                "Evaporator Fan State",
                "Door State",
                "Door Lock State",
                "UI Lock Mode",
                "Run Beep On Appliance",
                "Alert Event",
                "Alert Event Log",
                "Alert Event Acknowledge",
                "NIU Alert Event",
                "Engineering Log 1",
                "Engineering Log 2",
                "Engineering Log 3",
                "Engineering Log 4",
                "Alert history w/o timestamp",
                "Alert Event Description",
                "Current Time",
                "Time Zone Parameters",
                "Local Time",
                "Cavity Light State",
                "Accent Light",
                "Compressor Speed",
                "Compressor State",
                "Compressor Runtime",
                "BootUp Counter",
                "Credentials Counter",
                "Network Counter",
                "Cloud Link Counter",
                "Appliance Boot State",
                "Appliance Total Working Time",
                "Smart Grid Reduced Load Time",
                "Smart Grid Delay Load Time",
                "Smart Grid Override",
                "Notification String",
                "Appliance Show Up",
                "Cumulative Water Consumption",
                "Water Hardness",
                "Water Level",
                "Water Tank Empty",
                "Water Tray Inserted",
                "Total Cycle Counter",
                "Trip Cycle Counter",
                "FPS-Fast Mode",
                "FPS-Icemaker State",
                "FPS-Icemaker Detailed State",
                "FPS-Water Filter State",
                "FPS-Water Filter State Reset",
                "FPS-Air Filter State",
                "FPS-Air Filter State Reset",
                "FPS-Convertible State",
                "FPS-Defrost Temperature",
                "FPS-Ice Dispenser State",
                "FPS-Water Dispenser State",
                "FPS-Fast Mode Time To End",
                "FPS-Humidity Feature Mode",
                "FPS-Last Defrost Time",
                "FPS-Door Open Accumulated Time",
                "FPS-Defrost Routine State",
                "FPS-Next Defrost Target Time",
                "FPS-Cooling Valve State",
                "AC-Mode",
                "AC-Fan Speed Setting",
                "AC-Fan Speed State",
                "AC-Clean Air Mode",
                "AC-Flap Oscillate",
                "AC-Flap Speed",
                "AC-Flap Position",
                "AC-Vertical Swing Mode",
                "AC-Horizontal Swing Mode",
                "AC-Four Way Valve State",
                "AC-Electric Heater State",
                "AC-Evaporator Defrost State",
                "AC-Clean Filter Alert",
                "AC-Filter State Reset",
                "AC-Compressor Cooling Runtime",
                "AC-Compressor Heating Runtime",
                "AC-Electric Heater Runtime",
                "AC-Demand Response",
                "AC-Scheduler Mode",
                "AC-Scheduler Defaults",
                "AC-Scheduler Event Count",
                "AC-Scheduler Event Sunday",
                "AC-Scheduler Event Monday",
                "AC-Scheduler Event Tuesday",
                "AC-Scheduler Event Wednesday",
                "AC-Scheduler Event Thursday",
                "AC-Scheduler Event Friday",
                "AC-Scheduler Event Saturday",
                "AC-Scheduler Event One Time",
                "AC-Scheduler Week Scheduler",
                "AC-Clear Schedule",
                "AC-Generic msg for service",
                "FPP-KitchenTimer",
                "FPP-User Preference Offset",
                "FPP-Food Probe Continue Cook",
                "FPP-Kitchen Timer Cancel",
                "FPP-Kitchen Timer Add 1Minute",
                "FPP-Oven Function Phase 1",
                "FPP-Oven Function Phase 2",
                "FPP-Oven Function Phase 3",
                "FPP-Oven Function Curr.Phase",
                "FPP-Air Guard",
                "FPP-Preheat Complete",
                "FPP-Food Probe Temperature",
                "FPP-Display Food Probe Temp.",
                "FPP-Target Food Probe Temp.",
                "FPP-Food Probe Insert. State",
                "FPP-Oven Cooking Process Id",
                "FPP-Cook Feat Set and Go",
                "FPP-Cook Feat Fast Heat Up",
                "Hold",
                "FPP-Cook Feat Time extension",
                "FPP-Cook Process State",
                "FPP-Cleaning Reminder Counter",
                "FPP-Descaling Reminder Countr",
                "FPP-New Recipe Data Size",
                "FPP-New Recipe Data Piece",
                "FPP-Heating Qualitative Level",
                "FPP-Heating Zone Descriptor",
                "FPP-Hob To Hood (H2H) State",
                "FPP-Hob To Hood (H2H) Mode",
                "DC-Favorite Cycle",
                "DC-Cycle Settings",
                "DC-Cycle Running states",
                "DC-Rinseaid Container State",
                "DC-Rinse Aid Level",
                "DC-Statistical Records",
                "DC-Cycle Phase",
                "DC-User Selections",
                "DC-Favorite User Selections",
                "DC-Service Error History Log",
                "DC-Rinse Aid Level",
                "DC-Display On Floor",
                "FC-Washer Curr.Cycle Settings",
                "FC-Dryer Current Cycle",
                "FC-Washer Phase and Sub-Phase",
                "FC-Dryer Phase and Sub-Phase",
                "FC-Washer Program Parameters",
                "FC-Dryer Program Parameters",
                "FC-Washer Spin Speed",
                "FC-User Selections",
                "FC-Program Parameters",
                "FC-Cycle Phase",
                "FC-Cycle Sub-Phase",
                "FC-Wash. Nominal Load Weight",
                "FC-Drying Nominal Load Weight",
                "FC-Measured Load Weight",
                "FC-Skip Phase",
                "FC-Skip Step",
                "FC-Water Tank Warning Mode",
                "FC-Hot Water Inlet Mode",
                "FC-Water Softener Mode",
                "FC-Max Detergent 1 Dose",
                "FC-Max Detergent 2 Dose",
                "FC-Current Detergent 1 Dose",
                "FC-Current Detergent 2 Dose",
                "FC-Miscellaneous",
                "FC-Top Load Door Position",
                "FC-Default Extra Rinse",
                "PLS-ELS Address",
                "PLS-ELS Mode",
                "PLS-Pay Per Unit (PPU) State",
                "PLS-Pay Per Unit (PPU) Info",
                "PLS-Out Of Operation",
                "PLS-Service Mode",
                "PLS-Current Alert",
                "Pass through"
        };
    }
}
